project:
  type: website
  output-dir: docs
  
website:
  title: "Latent class analysis"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Special topics"
        contents:
          - em-height.qmd
          - em-categorical.qmd
          - loglinear-LCA.qmd
          - local-dependence.qmd
          - clustering-distance.qmd
      - section: "Assignments"
        contents:
          - antireli-assignment.qmd
          - ESS-assignment.qmd
          - latent-profile.qmd
          - project-reproduce-LCA.qmd
      - section: "Applications"
        contents:
          - antireli.qmd
          - protest-ESS.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto  # re-render only when source changes